student_data = [
    {
        "student_no": "001",
        "first_name": "Aisha",
        "middle_name": "Adamu",
        "last_name": "Sunusi",
        "sex": "Female",
        "dob": "05-02-2017",
        "home_address": "23 Sharada Garu",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aliyu.jpg",
        "allergies": "Peanuts",
        "special_needs": "Glasses",
        "emergency_no": "0987654321",
        "student_class": "preNursery",
    },
    {
        "student_no": "002",
        "first_name": "Hassan",
        "middle_name": "Ali",
        "last_name": "Sunusi",
        "sex": "Male",
        "dob": "07-03-2018",
        "home_address": "45 Alu Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/hassan.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0687218842",
        "student_class": "Nursery1",
    },
    {
        "student_no": "003",
        "first_name": "Fatima",
        "middle_name": "",
        "last_name": "Abdullahi",
        "sex": "Female",
        "dob": "02-04-2019",
        "home_address": "12 Sharada Garu",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/fatima.jpg",
        "allergies": "Milk",
        "special_needs": "None",
        "emergency_no": "0987654321",
        "student_class": "preNursery2",
    },
    {
        "student_no": "004",
        "first_name": "Usman",
        "middle_name": "Sule",
        "last_name": "Mohammed",
        "sex": "Male",
        "dob": "12-08-2017",
        "home_address": "7 Ring Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/usman.jpg",
        "allergies": "Eggs",
        "special_needs": "None",
        "emergency_no": "0705476543",
        "student_class": "Nursery1",
    },
    {
        "student_no": "005",
        "first_name": "Amina",
        "middle_name": "Yusuf",
        "last_name": "Bello",
        "sex": "Female",
        "dob": "19-01-2018",
        "home_address": "30 Zoo Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/amina.jpg",
        "allergies": "Fish",
        "special_needs": "None",
        "emergency_no": "0812345678",
        "student_class": "Nursery2",
    },
    {
        "student_no": "006",
        "first_name": "Ibrahim",
        "middle_name": "Bello",
        "last_name": "Musa",
        "sex": "Male",
        "dob": "08-06-2019",
        "home_address": "15 Zaria Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/ibrahim.jpg",
        "allergies": "None",
        "special_needs": "Hearing Aid",
        "emergency_no": "0909876543",
        "student_class": "Nursery2",
    },
    {
        "student_no": "007",
        "first_name": "Zainab",
        "middle_name": "Ibrahim",
        "last_name": "Yusuf",
        "sex": "Female",
        "dob": "15-11-2017",
        "home_address": "8 Maiduguri Lane",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/zainab.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "preNursery",
    },
    {
        "student_no": "008",
        "first_name": "Abdul",
        "middle_name": "Sani",
        "last_name": "Ahmed",
        "sex": "Male",
        "dob": "03-09-2018",
        "home_address": "25 Bauchi Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/abdul.jpg",
        "allergies": "Pollen",
        "special_needs": "None",
        "emergency_no": "0809876543",
        "student_class": "preNursery2",
    },
    {
        "student_no": "009",
        "first_name": "Aisha",
        "middle_name": "Mustapha",
        "last_name": "Abubakar",
        "sex": "Female",
        "dob": "22-05-2019",
        "home_address": "14 Gwarzo Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aisha.jpg",
        "allergies": "Shellfish",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "preNursery",
    },
    {
        "student_no": "010",
        "first_name": "Yusuf",
        "middle_name": "Suleiman",
        "last_name": "Dauda",
        "sex": "Male",
        "dob": "09-12-2017",
        "home_address": "5 Wudil Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/yusuf.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "preNursery",
    },
    {
        "student_no": "011",
        "first_name": "Musa",
        "middle_name": "Bello",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "01-01-2013",
        "home_address": "18 Tudun Wada Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/musa.jpg",
        "allergies": "Peanuts",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "012",
        "first_name": "Fati",
        "middle_name": "Yakubu",
        "last_name": "Sule",
        "sex": "Female",
        "dob": "02-02-2013",
        "home_address": "15 Kurna Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/fati.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "013",
        "first_name": "Nuhu",
        "middle_name": "Abubakar",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "03-03-2013",
        "home_address": "21 Sabon Gari Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/nuhu.jpg",
        "allergies": "Milk",
        "special_needs": "None",
        "emergency_no": "0909876543",
        "student_class": "Primary1",
    },
    {
        "student_no": "014",
        "first_name": "Rukayya",
        "middle_name": "Abdullahi",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "04-04-2013",
        "home_address": "9 Zoo Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/rukayya.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "015",
        "first_name": "Yusuf",
        "middle_name": "Abubakar",
        "last_name": "Suleiman",
        "sex": "Male",
        "dob": "05-05-2013",
        "home_address": "11 Sabon Gari Lane",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/yusuf.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "016",
        "first_name": "Amina",
        "middle_name": "Musa",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "06-06-2013",
        "home_address": "10 Tudun Wada Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/amina.jpg",
        "allergies": "Eggs",
        "special_needs": "None",
        "emergency_no": "0709876543",
        "student_class": "Primary3",
    },
    {
        "student_no": "017",
        "first_name": "Ismail",
        "middle_name": "Yusuf",
        "last_name": "Sule",
        "sex": "Male",
        "dob": "07-07-2013",
        "home_address": "14 Zoo Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/ismail.jpg",
        "allergies": "Pollen",
        "special_needs": "None",
        "emergency_no": "0812345678",
        "student_class": "Primary3",
    },
    {
        "student_no": "018",
        "first_name": "Aisha",
        "middle_name": "Abdul",
        "last_name": "Sunusi",
        "sex": "Female",
        "dob": "08-08-2013",
        "home_address": "22 Sharada Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aisha.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "019",
        "first_name": "Aliyu",
        "middle_name": "Mustapha",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "08-08-2013",
        "home_address": "22 Sharada Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aliyu.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "020",
        "first_name": "Amina",
        "middle_name": "Yusuf",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "09-09-2013",
        "home_address": "16 Tudun Wada Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/amina.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary3",
    },
    {
        "student_no": "021",
        "first_name": "Ibrahim",
        "middle_name": "Bello",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "10-10-2013",
        "home_address": "19 Zoo Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/ibrahim.jpg",
        "allergies": "Peanuts",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "022",
        "first_name": "Fati",
        "middle_name": "Abubakar",
        "last_name": "Sule",
        "sex": "Female",
        "dob": "11-11-2013",
        "home_address": "24 Sabon Gari Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/fati.jpg",
        "allergies": "Milk",
        "special_needs": "None",
        "emergency_no": "0909876543",
        "student_class": "Primary1",
    },
    {
        "student_no": "023",
        "first_name": "Nuhu",
        "middle_name": "Yakubu",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "12-12-2013",
        "home_address": "20 Tudun Wada Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/nuhu.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "024",
        "first_name": "Rukayya",
        "middle_name": "Ismail",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "13-01-2014",
        "home_address": "17 Kurna Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/rukayya.jpg",
        "allergies": "Eggs",
        "special_needs": "None",
        "emergency_no": "0709876543",
        "student_class": "Primary2",
    },
    {
        "student_no": "025",
        "first_name": "Yusuf",
        "middle_name": "Ali",
        "last_name": "Suleiman",
        "sex": "Male",
        "dob": "14-02-2014",
        "home_address": "23 Sabon Gari Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/yusuf.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0812345678",
        "student_class": "Primary3",
    },
    {
        "student_no": "026",
        "first_name": "Aisha",
        "middle_name": "Abubakar",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "15-03-2014",
        "home_address": "18 Zoo Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aisha.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "027",
        "first_name": "Aliyu",
        "middle_name": "Musa",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "16-04-2014",
        "home_address": "25 Tudun Wada Lane",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aliyu.jpg",
        "allergies": "Pollen",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "028",
        "first_name": "Amina",
        "middle_name": "Yusuf",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "17-05-2014",
        "home_address": "21 Sabon Gari Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/amina.jpg",
        "allergies": "Milk",
        "special_needs": "None",
        "emergency_no": "090987654",
    },
    {
        "student_no": "029",
        "first_name": "Ibrahim",
        "middle_name": "Bello",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "18-06-2014",
        "home_address": "19 Tudun Wada Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/ibrahim.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary3",
    },
    {
        "student_no": "030",
        "first_name": "Fati",
        "middle_name": "Abubakar",
        "last_name": "Sule",
        "sex": "Female",
        "dob": "19-07-2014",
        "home_address": "24 Sabon Gari Street",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/fati.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "031",
        "first_name": "Nuhu",
        "middle_name": "Yakubu",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "20-08-2014",
        "home_address": "20 Tudun Wada Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/nuhu.jpg",
        "allergies": "Eggs",
        "special_needs": "None",
        "emergency_no": "0709876543",
        "student_class": "Primary1",
    },
    {
        "student_no": "032",
        "first_name": "Rukayya",
        "middle_name": "Ismail",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "21-09-2014",
        "home_address": "17 Kurna Avenue",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/rukayya.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0701122334",
        "student_class": "Primary2",
    },
    {
        "student_no": "033",
        "first_name": "Yusuf",
        "middle_name": "Ali",
        "last_name": "Suleiman",
        "sex": "Male",
        "dob": "22-10-2014",
        "home_address": "23 Sabon Gari Close",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/yusuf.jpg",
        "allergies": "Pollen",
        "special_needs": "None",
        "emergency_no": "0812345678",
        "student_class": "Primary3",
    },
    {
        "student_no": "034",
        "first_name": "Aisha",
        "middle_name": "Abubakar",
        "last_name": "Ibrahim",
        "sex": "Female",
        "dob": "23-11-2014",
        "home_address": "18 Zoo Road",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aisha.jpg",
        "allergies": "None",
        "special_needs": "None",
        "emergency_no": "0901122334",
        "student_class": "Primary1",
    },
    {
        "student_no": "035",
        "first_name": "Aliyu",
        "middle_name": "Musa",
        "last_name": "Sani",
        "sex": "Male",
        "dob": "24-12-2014",
        "home_address": "25 Tudun Wada Lane",
        "city": "Kano",
        "state": "Kano",
        "picture": "https://example.com/aliyu.jpg",
        "allergies": "Milk",
        "special_needs": "None",
        "emergency_no": "0801122334",
        "student_class": "Primary1",
    },
]


for record in student_data:
    if " " in record["dob"]:
        print("Whitespace found in date:", record["dob"])
    else:
        print("ALL OKAY!!!")
