# Generated by Django 4.2.9 on 2024-01-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_no", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("home_address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("KN", "Kano"),
                            ("JI", "Jigawa"),
                            ("AB", "Abia"),
                            ("AD", "Adamawa"),
                            ("AK", "Akwa Ibom"),
                            ("AN", "Anambra"),
                            ("BA", "Bauchi"),
                            ("BE", "Benue"),
                            ("BO", "Borno"),
                            ("CR", "Cross River"),
                            ("DE", "Delta"),
                            ("EB", "Ebonyi"),
                            ("ED", "Edo"),
                            ("EK", "Ekiti"),
                            ("EN", "Enugu"),
                            ("FC", "Federal Capital Territory"),
                            ("GO", "Gombe"),
                            ("IM", "Imo"),
                            ("JI", "Jigawa"),
                            ("KA", "Kaduna"),
                            ("KN", "Katsina"),
                            ("KE", "Kebbi"),
                            ("KO", "Kogi"),
                            ("KW", "Kwara"),
                            ("LA", "Lagos"),
                            ("NA", "Nasarawa"),
                            ("NI", "Niger"),
                            ("OG", "Ogun"),
                            ("ON", "Ondo"),
                            ("OS", "Osun"),
                            ("OY", "Oyo"),
                            ("PL", "Plateau"),
                            ("RI", "Rivers"),
                            ("SO", "Sokoto"),
                            ("TA", "Taraba"),
                            ("YO", "Yobe"),
                            ("ZA", "Zamfara"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_pictures/"
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("special_needs", models.TextField(blank=True, null=True)),
                ("emergency_no", models.CharField(max_length=15)),
                (
                    "student_class",
                    models.CharField(
                        choices=[
                            ("preNursery", "PreNursery"),
                            ("nurseryOne", "Nursery1"),
                            ("nurseryTwo", "Nursery2"),
                            ("PrimaryOne", "Primary1"),
                            ("PrimaryTwo", "Primary2"),
                            ("PrimaryThree", "Primary3"),
                            ("PrimaryFour", "Primary4"),
                            ("PrimaryFive", "Primary5"),
                            ("PrimarySix", "Primary6"),
                            ("Senior", "Senior"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
