# Generated by Django 4.2.9 on 2024-01-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(
                choices=[("KN", "Kano"), ("JI", "Jigawa"), ("AB", "Abia")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.CharField(
                choices=[
                    ("preNursery", "PreNursery"),
                    ("nurseryOne", "Nursery1"),
                    ("nurseryTwo", "Nursery2"),
                ],
                max_length=20,
            ),
        ),
    ]
